import React from 'react';
import Head from 'next/head';
import styles from '@/styles/Pages.module.css';

type PageProps = {
  title?: string;
  description?: string;
  children: React.ReactNode;
};

export default function Page({ 
  title = 'Create Next App',
  description = 'Generated by create next app',
  children
}: PageProps) {
  return (
    <>
      <Head>
        <title>{title}</title>
        <meta name="description" content={description} />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>{children}</main>
    </>
  );
}
